=== oss6/metaboflow/workflow-configuration.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "data_path": {
      "type": "string",
      "description": "The path of the data, either as a directory or a zip file."
    },
    "filelist_path": {
      "type": "string",
      "description": "The path of the metadata file."
    },
    "scans_path": {
      "type": "string",
      "description": "The path where to save or read processed scans."
    },
    "use_scans_path": {
      "type": "boolean",
      "description": "Whether to use the scans path."
    },
    "factor_name": {
      "type": "string",
      "description": "The factor name that decides the samples."
    },
    "qc_label": {
      "type": "string",
      "description": "The quality control label in the samples."
    },
    "galaxy": {
      "type": "object",
      "description": "Galaxy workflow running configuration.",
      "properties": {
        "enabled": {
          "type": "boolean",
          "description": "Whether to enable Galaxy workflow running."
        },
        "api_key": {
          "type": "string",
          "description": "The Galaxy API key."
        },
        "history_name": {
          "type": "string",
          "description": "The created history name."
        }
      }
    },
    "skip_processing": {
      "type": "boolean",
      "description": "Whether to skip data processing."
    },
    "output_directory": {
      "type": "string",
      "description": "The output directory path."
    },
    "process_scans": {
      "type": "object",
      "description": "Process scans step configuration.",
      "properties": {
        "function_noise": {
          "type": "string"
        },
        "snr_thres": {
          "type": "number"
        },
        "ppm": {
          "type": "number"
        },
        "min_fraction": {
          "type": "number"
        },
        "min_scans": {
          "type": "integer"
        }
      },
      "required": [
        "function_noise",
        "snr_thres",
        "ppm",
        "min_fraction",
        "min_scans"
      ]
    },
    "replicate_filter": {
      "type": "object",
      "description": "Replicate filter scans configuration.",
      "properties": {
        "replicates": {
          "type": "integer"
        },
        "min_peaks": {
          "type": "integer"
        },
        "ppm": {
          "type": "number"
        },
        "rsd_thres": {
          "type": "null"
        }
      },
      "required": [
        "replicates",
        "min_peaks",
        "ppm",
        "rsd_thres"
      ]
    },
    "align_samples": {
      "type": "object",
      "description": "Align samples step configuration.",
      "properties": {
        "ppm": {
          "type": "number"
        }
      },
      "required": [
        "ppm"
      ]
    },
    "blank_filter": {
      "type": "object",
      "description": "Blank filter step configuration",
      "properties": {
        "label": {
          "type": "string"
        },
        "min_fold_change": {
          "type": "number"
        },
        "min_fraction": {
          "type": "number"
        },
        "function": {
          "type": "string"
        }
      },
      "required": [
        "label",
        "min_fold_change",
        "min_fraction",
        "function"
      ]
    },
    "sample_filter": {
      "type": "object",
      "description": "Sample filter step configuration.",
      "properties": {
        "min_fraction": {
          "type": "number"
        }
      },
      "required": [
        "min_fraction"
      ]
    },
    "imputation": {
      "type": "object",
      "description": "Missing values imputation configuration.",
      "properties": {
        "neighbours": {
          "type": "integer"
        },
        "feature_max": {
          "type": "number"
        },
        "sample_max": {
          "type": "number"
        }
      },
      "required": [
        "neighbours",
        "feature_max",
        "sample_max"
      ]
    },
    "normalisation": {
      "type": "object",
      "description": "Normalisation step configuration.",
      "properties": {
        "type": {
          "type": "string"
        },
        "qc_label": {
          "type": "string"
        },
        "factor_name": {
          "type": "string"
        },
        "scaling_factor": {
          "type": "number"
        }
      },
      "required": [
        "type"
      ]
    },
    "transform": {
      "type": "object",
      "description": "Transform step configuration.",
      "properties": {
        "type": {
          "type": "string"
        },
        "qc_label": {
          "type": "string"
        },
        "factor_name": {
          "type": "string"
        },
        "base": {
          "type": "integer"
        },
        "root": {
          "type": "integer"
        }
      },
      "required": [
        "type"
      ]
    },
    "scaling": {
      "type": "object",
      "description": "Scaling step configuration.",
      "properties": {
        "type": {
          "type": "string"
        }
      },
      "required": [
        "type"
      ]
    },
    "t_test": {
      "type": "object",
      "description": "t-test configuration.",
      "properties": {
        "alpha": {
          "type": "number"
        }
      }
    }
  }
}

=== oss6/metaboflow/examples/workflow-configuration2.json
{
  "data_path": "examples/batch_06.zip",
  "filelist_path": "examples/filelist_batch_06.txt",
  "use_scans_path": false,
  "factor_name": "classLabel",
  "qc_label": "QC",
  "galaxy": {
    "enabled": true,
    "api_key": "YOUR API KEY",
    "history_name": "Process metabolomics data (2)"
  },
  "skip_processing": false,
  "output_directory": "out_2",
  "process_scans": {
    "function_noise": "median",
    "snr_thres": 2.5,
    "ppm": 4.0,
    "min_fraction": 0.0,
    "min_scans": 1
  },
  "replicate_filter": {
    "replicates": 3,
    "min_peaks": 2,
    "ppm": 2.0,
    "rsd_thres": null
  },
  "align_samples": {
    "ppm": 2.0
  },
  "blank_filter": {
    "label": "blank",
    "min_fold_change": 10.0,
    "min_fraction": 1.0,
    "function": "mean"
  },
  "sample_filter": {
    "min_fraction": 0.8
  },
  "imputation": {
    "neighbours": 10,
    "feature_max": 50,
    "sample_max": 50
  },
  "normalisation": {
    "type": "pqn",
    "qc_label": "QC",
    "factor_name": "classLabel"
  },
  "transform": {
    "type": "glog",
    "qc_label": "QC",
    "factor_name": "classLabel"
  },
  "scaling": {
    "type": "mean"
  },
  "t_test": {
    "alpha": 0.05
  }
}

=== oss6/metaboflow/examples/workflow-configuration5.json
{
  "$schema": "../workflow-configuration.schema.json",
  "data_path": "examples/batch_06.zip",
  "filelist_path": "examples/filelist_batch_06.txt",
  "scans_path": "examples/w5-scans.h5",
  "use_scans_path": false,
  "factor_name": "classLabel",
  "qc_label": "QC",
  "skip_processing": false,
  "output_directory": "out_5",
  "process_scans": {
    "function_noise": "mean",
    "snr_thres": 3.0,
    "ppm": 2.8,
    "min_fraction": 0.0,
    "min_scans": 1
  },
  "replicate_filter": {
    "replicates": 3,
    "min_peaks": 2,
    "ppm": 2.8,
    "rsd_thres": null
  },
  "align_samples": {
    "ppm": 2.8
  },
  "blank_filter": {
    "label": "blank",
    "min_fold_change": 11.0,
    "min_fraction": 1.0,
    "function": "mean"
  },
  "sample_filter": {
    "min_fraction": 0.8
  },
  "imputation": {
    "neighbours": 10,
    "feature_max": 50,
    "sample_max": 50
  },
  "normalisation": {
    "type": "pqn",
    "qc_label": "QC",
    "factor_name": "classLabel"
  },
  "transform": {
    "type": "glog",
    "qc_label": "QC",
    "factor_name": "classLabel"
  },
  "scaling": {
    "type": "mean"
  },
  "t_test": {
    "alpha": 0.05
  }
}
